### ISSUE TITLE
Not able to run pin_compare.py script

### ISSUE THREAD

**Issue by Kapil-K-Kathiriya** [Ledger-Donjon/rainbow#46] opened 2023-06-15 10:25 UTC
![image](https://github.com/Ledger-Donjon/rainbow/assets/83130959/d7da5d64-b9da-4f74-acf0-b3625b34b40d)

Please look at attach a screenshot of the error and provide a solution... Thank you

**Comment by yhql** [comment] 2023-06-19 13:31
I could not reproduce your specific problem, but now that an update has been merged, you can try again on this https://github.com/Ledger-Donjon/rainbow/pull/47 to see whether it works ?

**Comment by Kapil-K-Kathiriya** [comment] 2023-06-22 13:08
I have tried updated code, but it still gets some TypeError; please look at attached screenshot

![image](https://github.com/Ledger-Donjon/rainbow/assets/83130959/091e2a75-3c21-485a-9aae-39cada55121d)

**Comment by yhql** [comment] 2023-06-22 13:13
I suspect your version is Rainbow is not up-to-date for this example

**Comment by yhql** [comment] 2023-06-22 13:19
(mixed up Rainbow with Lascar. You should update Lascar)
`python -m pip install git+https://github.com/Ledger-Donjon/lascar`

**Comment by Kapil-K-Kathiriya** [comment] 2023-06-23 11:21
I have updated lascar, but it still gives the same error.
For your clarification, I would like to mention the step I did, so if you see any invalid steps, please let me know.
1) Download the git repo as a zip file for this project from [https://github.com/Ledger-Donjon/lascar](url)
2) Unzip that file in my local system and then install the setup.py file using `python setup.py install`
3) Then I run `python -m pip install git+https://github.com/Ledger-Donjon/lascar` command
4) Then I run pin_compare.py using command `python pin_compare.py`

I have also checked the lascar version it is 1.1 and Rainbow version is 2.0

**Comment by Kapil-K-Kathiriya** [comment] 2023-06-26 06:13
I appreciate your support, now I am able to run successfully.

**Closed** 2023-06-26 06:12 UTC
